CREATE DATABASE IF NOT EXISTS bora_rachao CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bora_rachao;
CREATE TABLE IF NOT EXISTS users (
	id_user BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    document VARCHAR(30) NOT NULL UNIQUE,
    city VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    bio TEXT,
    gender VARCHAR(30),
    avatar VARCHAR(255),
    friends_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS sports (
	id_sport BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE,
    description TEXT,
    image VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS events (
	id_event BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    sport_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(255),
    description TEXT,
    status VARCHAR(50),
    event_date DATETIME NOT NULL,
    min_age TINYINT UNSIGNED,
    max_players TINYINT UNSIGNED,
    players_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    visibility VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    FOREIGN KEY (sport_id) REFERENCES sports (id_sport),
    FOREIGN KEY (user_id) REFERENCES users (id_user)
);
CREATE TABLE IF NOT EXISTS event_addresses (
	id_event_address BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    event_id BIGINT UNSIGNED NOT NULL,
    zip_code VARCHAR(20) NOT NULL,
    house_number VARCHAR(20) NOT NULL,
    street VARCHAR(255) NOT NULL,
    neighborhood VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events (id_event)
);
CREATE TABLE IF NOT EXISTS event_players (
	id_event_player BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    event_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events (id_event),
    FOREIGN KEY (user_id) REFERENCES users (id_user)
);
CREATE TABLE IF NOT EXISTS friends (
	id_friend BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT UNSIGNED NOT NULL,
    friend_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id_user),
    FOREIGN KEY (friend_id) REFERENCES users (id_user),
);